name: BCHDeploy

on: 
  push:
    branches: site

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Package 
      run: pwd & ls -al && chmod a+x packblog.sh & bash packblog.sh ${{secrets.BCH_DB_HOST}} ${{secrets.BCH_DB_ACCOUNT}} ${{secrets.BCH_PASSWORD}}
    
    - name: Upload to BCH
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{secrets.BCH_ACCOUNT}}.ftp01.bcehost.com
        FTP_USERNAME: ${{secrets.BCH_ACCOUNT}}
        FTP_PASSWORD: ${{secrets.BCH_PASSWORD}}
        LOCAL_DIR: FinalBuild
        REMOTE_DIR: webroot/packzip
        
    - name: Trigger Deploy
      run: chmod a+x publish.sh & bash publish.sh ${{secrets.DEPLOY_HOST}}