name: BCHDeploy

on: 
  push:
    branches: site

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
  
  deploy:
 
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Package 
      run: bash packblog.sh 
